services:
  migrate:
    build:
      target: development
    environment:
      NODE_ENV: development
    command: ['npm', 'run', 'migration:run']
  app:
    build:
      target: development
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    command: ['npm', 'run', 'dev']
